### PR TITLE
Add myself (Surbeck Léon) to the Student list of DAI

### LINKED ISSUE #130: Add myself (Surbeck Léon) to the list of students
I would like to add myself to the list of students in the GitHub organization README.

### PR DESCRIPTION
**Pull request by Bananonymous**
Fixes #130

### CODE REVIEW

**Comment by Bananonymous** [comment]
@ludelafo @hadrylouis :)

**Comment by ludelafo** [comment]
It seems your commits cannot be verified. Please ensure you have added a **signing key** to your GitHub settings as mentioned in the course material: https://github.com/heig-vd-dai-course/heig-vd-dai-course/blob/main/03-git-github-and-markdown/COURSE_MATERIAL.md#add-a-new-ssh-signing-key-to-your-github-account.

**Comment by Bananonymous** [comment]
Thanks, I thought it was already done, the key was "Already used" on Github, I changed it, Do I need to redo steps ? Or should it update by itself ?

**Comment by hadrylouis** [comment]
It seems good to me :)

**Review by hadrylouis — APPROVED** [review]

**Pull request merged**
