### PR TITLE
Add myself (Drin Racaj) to the list of students

### LINKED ISSUE #129: Add myself (Drin Racaj) to the list of students
I would like to add myself to the list of students in the GitHub organization README.

### PR DESCRIPTION
**Pull request by drinracaj**
Fixes #129, or Closes #129

### CODE REVIEW

**Comment by drinracaj** [comment]
@ludelafo @hadrylouis @GeraudSilvestri

**Review by ludelafo — CHANGES_REQUESTED** [review]
It seems your commits cannot be verified. Please ensure you have added a signing key to your GitHub settings as mentioned in the course material: https://github.com/heig-vd-dai-course/heig-vd-dai-course/blob/main/03-git-github-and-markdown/COURSE_MATERIAL.md#add-a-new-ssh-signing-key-to-your-github-account.

**Review by ludelafo — APPROVED** [review]

**Review by ludelafo — CHANGES_REQUESTED** [review]
My bad, I thought everything was OK but the commits still need to be verified.

**Comment by ludelafo** [comment]
As the latest commit is verified, all good! Sorry about the confusion.

**Review by ludelafo — APPROVED** [review]

**Pull request merged**
