### PR TITLE
Add myself to the list of students

### LINKED ISSUE #87: Add myself (Sara Camassa) to the list of students
I would like to add myself to the list of students in the GitHub organization README.

### PR DESCRIPTION
**Pull request by scamassa**
Fixes #87

### CODE REVIEW

**Review by GeraudSilvestri — CHANGES_REQUESTED** [review]
It seems you haven't signed your commit? Can you please check that it is enabled, working and update the current PR?

**Comment by ludelafo** [comment]
As @GeraudSilvestri mentioned, it seems you haven't signed your commits at all. Please follow the course material to enable this: https://github.com/heig-vd-dai-course/heig-vd-dai-course/blob/main/03-git-github-and-markdown/COURSE_MATERIAL.md#sign-commits-with-ssh.

To sign all previous commits, you can use the tip mentioned in the course material here: https://github.com/heig-vd-dai-course/heig-vd-dai-course/blob/main/03-git-github-and-markdown/COURSE_MATERIAL.md#make-changes-if-needed.

**Comment by scamassa** [comment]
Hello @ludelafo @GeraudSilvestri , I have tried multiple times to follow the instructions and sign my commits but it didn't work. I am not sure what I am doing wrong, I will try again later but I still don't know the problem.

**Comment by ludelafo** [comment]
> Hello @ludelafo @GeraudSilvestri , I have tried multiple times to follow the instructions and sign my commits but it didn't work. I am not sure what I am doing wrong, I will try again later but I still don't know the problem.

No worries, we'll find out why it doesn't work. Please let us know if you were able to fix it. If not, I'm available tomorrow morning (Tuesday 24.09) for a Teams call to help you if needed.

**Pull request closed without merging**
