### PR TITLE
Add myself (Gonçalo Heleno) to the list of students

### LINKED ISSUE #80: Add myself (Gonçalo Heleno) to the list of students
I would like to add myself to the list of students in the GitHub organization README.

### PR DESCRIPTION
**Pull request by lentidas**
Closes #80.

Two small notes:
- You may notice I used my full name when adding it to the README.md. I go by Heleno everywhere, however the school uses my two last names. As such, I thought you may find me in your lists by Carvalheiro instead of Heleno.
- My commit shows as `Unverified` because I've not added my school e-mail to my GPG key yet 😉

### CODE REVIEW

**Review by GeraudSilvestri — DISMISSED** [review]

**Comment by lentidas** [comment]
@ludelafo @GeraudSilvestri My PR is ready for review!

**Comment by GeraudSilvestri** [comment]
It seems you haven't signed your commit? Can you please check that it is enabled, working and update the current PR?

**Review by GeraudSilvestri — CHANGES_REQUESTED** [review]
It seems you haven't signed your commit? Can you please check that it is enabled, working and update the current PR?

**Comment by lentidas** [comment]
@ludelafo @GeraudSilvestri I've added my school e-mail to my GPG key. The commit should now show as verified. Do you want me to fix the merge conflicts?

**Review by GeraudSilvestri — APPROVED** [review]

**Pull request merged**
