### PR TITLE
Add @KevinFarine to the list of students

### PR DESCRIPTION
**Pull request by KevinFarine**
I did some test and try out some features

### CODE REVIEW

**Comment by hadrylouis** [comment]
It would be great if you can sign your previous commits. You can follow [this tutorial](https://stackoverflow.com/a/54987693)

**Comment by ludelafo** [comment]
Don't forget to associate the PR to its issue, you can do it from the right panel. :)

Oh and you can add us as reviewers!

**Comment by KevinFarine** [comment]
@ludelafo @hadrylouis
https://github.com/heig-vd-dai-course/.github/issues/9

**Comment by hadrylouis** [comment]
Could you please follow my previous link to sign all your previous commits. Then I will merge

**Comment by ludelafo** [comment]
As we squash the commits you did, the last one will be considered for the signing.

In the future, please ensure to sign all your commits @KevinFarine! I'll merge your work now.

**Review by ludelafo — APPROVED** [review]

**Pull request merged**
