### PR TITLE
Add myself to the list of students

### LINKED ISSUE #83: Add myself Mathieu Rabot to the list of students
I would like to add myself to the list of students in the GitHub organization README.

### PR DESCRIPTION
**Pull request by Nomeos**

### CODE REVIEW

**Review by ludelafo — APPROVED** [review]

**Review by ludelafo — CHANGES_REQUESTED** [review]
It seems you haven't signed your commit? Can you please check that it is enabled, working and update the current PR?

**Comment by GeraudSilvestri** [comment]
Closes #83

**Comment by Nomeos** [comment]
Update done

**Review by GeraudSilvestri — CHANGES_REQUESTED** [review]
You added yourself to the wrong DAI course. The friday morning DAI course is DAI-TIC-C

**Review by GeraudSilvestri — APPROVED** [review]

**Review by ludelafo — APPROVED** [review]

**Pull request merged**
