### PR TITLE
Add myself (Basile Buxtorf) to the list of students

### LINKED ISSUE #144: Add myself (Basile Buxtorf) to the list of students
I would like to add myself to the list of students in the GitHub organization README.

### PR DESCRIPTION
**Pull request by BasileBux**
#144

### CODE REVIEW

**Comment by BasileBux** [comment]
@ludelafo @hadrylouis

**Comment by hadrylouis** [comment]
It seems you haven't signed your commits at all. Please follow the course material to enable this: https://github.com/heig-vd-dai-course/heig-vd-dai-course/blob/main/03-git-github-and-markdown/COURSE_MATERIAL.md#sign-commits-with-ssh.

To sign all previous commits, you can use the tip mentioned in the course material here: https://github.com/heig-vd-dai-course/heig-vd-dai-course/blob/main/03-git-github-and-markdown/COURSE_MATERIAL.md#make-changes-if-needed.

**Comment by BasileBux** [comment]
I did this: 
`git rebase --exec "git commit --amend --no-edit -n -S" -i 890a4ae2bc1070a2e25f969900e9cc968fe9cfdf`
And it gave me this: 
`Successfully rebased and updated refs/heads/add-myself-to-the-list-of-students.`
I then pushed force, but it doesn't seem to have changed anything.

**Comment by hadrylouis** [comment]
You have used the right command but as mentioned in the course material, you should specify the previous commit hash from the `git log` command.

https://github.com/heig-vd-dai-course/heig-vd-dai-course/blob/main/03-git-github-and-markdown/COURSE_MATERIAL.md#make-changes-if-needed

**Review by hadrylouis — APPROVED** [review]

**Comment by hadrylouis** [comment]
Commits seem to be signed now. Good job.

You didn't add yourself to the right class. I fixed it for you.

**Pull request merged**
