### PR TITLE
Add myself Léonard Jouve to the list of students

### LINKED ISSUE #84: Add myself Léonard Jouve to the list of students
I would like to add myself to the list of students in the GitHub organization README.

### PR DESCRIPTION
**Pull request by LeonardJouve**
Closes #84

### CODE REVIEW

**Review by GeraudSilvestri — DISMISSED** [review]

**Comment by LeonardJouve** [comment]
@ludelafo
@hadrylouis
@GeraudSilvestri ready

**Comment by GeraudSilvestri** [comment]
It seems you haven't signed your commit? Can you please check that it is enabled, working and update the current PR?

**Review by GeraudSilvestri — CHANGES_REQUESTED** [review]
It seems you haven't signed your commit? Can you please check that it is enabled, working and update the current PR?

**Review by LeonardJouve — COMMENTED** [review]
Should be good now

**Review by GeraudSilvestri — APPROVED** [review]

**Pull request merged**
